apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    name: results-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30005
  selector:
    name: results-app-pod
    app: demo-voting-app