apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    name: worker-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    name: worker-app-pod
    app: demo-voting-app