apiVersion: v1
kind: Pod
metadata:
  name: results-app-pod
  labels:
    name: results-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: results-app-pod
      image: lmubarokah/results-service:latest
      ports:
        - containerPort: 8085
      env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "Barakat1243"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_DB_NEW
          value: "votingdb"