apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  name: redis
spec:
  replicas: {{ .Values.replicaCount }}
  #replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.repository }}
        # image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        #image: lukmanadeokun31/redis:latest
        ports:
          - containerPort: 6379
