apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    job: worker
    app: worker
spec:
  selector:
    app: worker
  ports:
    - name: web
      port: 8084
      protocol: TCP
      targetPort: 8084
  type: ClusterIP
